# Generated by Django 5.1.4 on 2024-12-20 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='personal.categoria'),
            preserve_default=False,
        ),
    ]
