# Generated by Django 5.1.4 on 2024-12-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_article_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
